version: '3.2'
services:
  back-end:
    container_name: mean_backend
    build: .
    volumes:
      - .:/backend
    ports:
      - 3000:3000
    command: yarn run start

  database:
    container_name: mean_db
    image: mongo
    ports:
      - 27017:27017
